### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by dedimark** [FortyTwoFortyTwo/Randomizer#122]
Randomizer - 1.11.3
SourceMod Version: 1.11.0.6957

L 06/22/2024 - 07:36:50: [SM] Call stack trace:
L 06/22/2024 - 07:36:50: [SM]   [0] ThrowError
L 06/22/2024 - 07:36:50: [SM]   [1] Line 270, randomizer\stocks.sp::TF2_GetSlot
L 06/22/2024 - 07:36:50: [SM]   [2] Line 215, randomizer\controls.sp::Controls_CanUse
L 06/22/2024 - 07:36:50: [SM]   [3] Line 532, randomizer\dhook.sp::DHook_DoClassSpecialSkillPre
L 06/22/2024 - 07:36:50: [SM]   [5] SDKCall
L 06/22/2024 - 07:36:50: [SM]   [6] Line 97, randomizer\sdkcall.sp::SDKCall_DoClassSpecialSkill
L 06/22/2024 - 07:36:50: [SM]   [7] Line 926, randomizer\dhook.sp::DHook_SecondaryWeaponPost
L 06/22/2024 - 07:36:50: [SM] Exception reported: Could not find slot from item def index '57' and classname 'tf_wearable'
L 06/22/2024 - 07:36:50: [SM] Blaming: tf2items_randomizer_x10.smx
L 06/22/2024 - 07:36:50: [SM] Call stack trace:
L 06/22/2024 - 07:36:50: [SM]   [0] ThrowError
L 06/22/2024 - 07:36:50: [SM]   [1] Line 270, randomizer\stocks.sp::TF2_GetSlot
L 06/22/2024 - 07:36:50: [SM]   [2] Line 215, randomizer\controls.sp::Controls_CanUse
L 06/22/2024 - 07:36:50: [SM]   [3] Line 532, randomizer\dhook.sp::DHook_DoClassSpecialSkillPre
L 06/22/2024 - 07:36:50: [SM]   [5] SDKCall
L 06/22/2024 - 07:36:50: [SM]   [6] Line 97, randomizer\sdkcall.sp::SDKCall_DoClassSpecialSkill
L 06/22/2024 - 07:36:50: [SM]   [7] Line 926, randomizer\dhook.sp::DHook_SecondaryWeaponPost
L 06/22/2024 - 07:36:50: [SM] Exception reported: Could not find slot from item def index '57' and classname 'tf_wearable'
L 06/22/2024 - 07:36:50: [SM] Blaming: randomizer.smx
L 06/22/2024 - 07:36:50: [SM] Call stack trace:
L 06/22/2024 - 07:36:50: [SM]   [0] ThrowError
L 06/22/2024 - 07:36:50: [SM]   [1] Line 270, randomizer\stocks.sp::TF2_GetSlot
L 06/22/2024 - 07:36:50: [SM]   [2] Line 215, randomizer\controls.sp::Controls_CanUse
L 06/22/2024 - 07:36:50: [SM]   [3] Line 532, randomizer\dhook.sp::DHook_DoClassSpecialSkillPre
L 06/22/2024 - 07:36:50: [SM]   [5] SDKCall
L 06/22/2024 - 07:36:50: [SM]   [6] Line 97, randomizer\sdkcall.sp::SDKCall_DoClassSpecialSkill
L 06/22/2024 - 07:36:50: [SM]   [7] Line 926, randomizer\dhook.sp::DHook_SecondaryWeaponPost
L 06/22/2024 - 07:36:50: [SM] Exception reported: Could not find slot from item def index '57' and classname 'tf_wearable'
L 06/22/2024 - 07:36:50: [SM] Blaming: randomizer.smx
L 06/22/2024 - 07:36:50: [SM] Call stack trace:
L 06/22/2024 - 07:36:50: [SM]   [0] ThrowError
L 06/22/2024 - 07:36:50: [SM]   [1] Line 270, randomizer\stocks.sp::TF2_GetSlot
L 06/22/2024 - 07:36:50: [SM]   [2] Line 215, randomizer\controls.sp::Controls_CanUse
L 06/22/2024 - 07:36:50: [SM]   [3] Line 532, randomizer\dhook.sp::DHook_DoClassSpecialSkillPre
L 06/22/2024 - 07:36:50: [SM]   [5] SDKCall
L 06/22/2024 - 07:36:50: [SM]   [6] Line 97, randomizer\sdkcall.sp::SDKCall_DoClassSpecialSkill
L 06/22/2024 - 07:36:50: [SM]   [7] Line 926, randomizer\dhook.sp::DHook_SecondaryWeaponPost
L 06/22/2024 - 07:36:50: [SM] Exception reported: Could not find slot from item def index '57' and classname 'tf_wearable'
L 06/22/2024 - 07:36:50: [SM] Blaming: randomizer.smx
L 06/22/2024 - 07:36:50: [SM] Call stack trace:
L 06/22/2024 - 07:36:50: [SM]   [0] ThrowError
L 06/22/2024 - 07:36:50: [SM]   [1] Line 270, randomizer\stocks.sp::TF2_GetSlot
L 06/22/2024 - 07:36:50: [SM]   [2] Line 215, randomizer\controls.sp::Controls_CanUse
L 06/22/2024 - 07:36:50: [SM]   [3] Line 532, randomizer\dhook.sp::DHook_DoClassSpecialSkillPre
L 06/22/2024 - 07:36:50: [SM]   [5] SDKCall
L 06/22/2024 - 07:36:50: [SM]   [6] Line 97, randomizer\sdkcall.sp::SDKCall_DoClassSpecialSkill
L 06/22/2024 - 07:36:50: [SM]   [7] Line 926, randomizer\dhook.sp::DHook_SecondaryWeaponPost
L 06/22/2024 - 07:36:50: [SM] Exception reported: Could not find slot from item def index '57' and classname 'tf_wearable'
L 06/22/2024 - 07:36:50: [SM] Blaming: randomizer.smx
L 06/22/2024 - 07:36:50: [SM] Call stack trace:
L 06/22/2024 - 07:36:50: [SM]   [0] ThrowError
L 06/22/2024 - 07:36:50: [SM]   [1] Line 270, randomizer\stocks.sp::TF2_GetSlot
L 06/22/2024 - 07:36:50: [SM]   [2] Line 215, randomizer\controls.sp::Controls_CanUse
L 06/22/2024 - 07:36:50: [SM]   [3] Line 532, randomizer\dhook.sp::DHook_DoClassSpecialSkillPre
L 06/22/2024 - 07:36:50: [SM]   [5] SDKCall
L 06/22/2024 - 07:36:50: [SM]   [6] Line 97, randomizer\sdkcall.sp::SDKCall_DoClassSpecialSkill
L 06/22/2024 - 07:36:50: [SM]   [7] Line 926, randomizer\dhook.sp::DHook_SecondaryWeaponPost

**Comment by FortyTwoFortyTwo** [comment]
> L 06/22/2024 - 07:36:50: [SM] Blaming: tf2items_randomizer_x10.smx

Where does this plugin comes from, and does it runs fine if you removed that plugin?

**Comment by FortyTwoFortyTwo** [comment]
I don't know what or where `tf2items_randomizer_x10` is, separate from my randomizer. I'm saying this as I'm suspecting that's what causes this error.

**Comment by FortyTwoFortyTwo** [comment]
I'm still suspecting that it's not my plugin generating weapon 57 (Razorback) using classname tf_wearable (should actually be tf_wearable_razorback). Do you know if `tf2items_randomizer_x10` or any other plugins is generating that weapon incorrectly?

**Comment by FortyTwoFortyTwo** [comment]
https://github.com/MoeVsMachine/TF2x10-steamworks/blob/4246674cd8495cbae104f1889a0565bf3f8bf36d/addons/sourcemod/scripting/tf2items_randomizer_x10.sp#L2084
https://github.com/MoeVsMachine/TF2x10-steamworks/blob/4246674cd8495cbae104f1889a0565bf3f8bf36d/addons/sourcemod/scripting/tf2x10.sp#L2060

These two should ideally be updated to use `tf_wearable_razorback` instead. I'm less keen to "fix" my randomizer just for this very specific case, unless if there are more similar cases to it.
