### ISSUE TITLE
Engi attempting to upgrade a building with a wrench crashes server

### ISSUE THREAD

**Issue by Djrulz0826** [FortyTwoFortyTwo/Randomizer#13]
Attempting to upgrade any building with any wrench as an engineer crashes the server.
Related log file:
[errors_20200830.log](https://github.com/FortyTwoFortyTwo/Randomizer/files/5147481/errors_20200830.log)

**Comment by FortyTwoFortyTwo** [comment]
asherkin's VTable dumper apparently made wrong offset for windows, so i fixed that. This bug does not occur in linux as it using correct offset.
Thanks for the report!
