### ISSUE TITLE
Popping phlog crits activates MvM projectile shield for medigun

### ISSUE THREAD

**Issue by Djrulz0826** [FortyTwoFortyTwo/Randomizer#14]
Using the phlogistinator's +attack2 with full rage and swapping to any medigun activates the projectile shield from MvM
Related video:
https://youtu.be/Lw2lp9Hl8NQ

**Comment by FortyTwoFortyTwo** [comment]
This happens because shield is using `m_flRageMeter` netprop for charge meter, sharing with phlogistinator, banners and Hitman Heatmaker.

May be best to resolve #7 first if possible, which this issue may get fixed along with it.
