### ISSUE TITLE
Teleporters remain bugged, even more so

### ISSUE THREAD

**Issue by Djrulz0826** [FortyTwoFortyTwo/Randomizer#16]
Teleporters not only do not setup properly, but also allow enemies to teleport.
Related videos:
https://youtu.be/LzISDG6x--c (Teleporter Setup)
https://youtu.be/DoAY8ME68xM (Enemy Teleporting)

**Comment by FortyTwoFortyTwo** [comment]
You sure your using version `1.4.0.139` or higher? I couldn't reproduce the setup bug myself by using same steps, by placing one teleporter, then changing loadout before build is complete.

**Comment by Djrulz0826** [comment]
Updated to 1.4.0.140, solved issue.
