### ISSUE TITLE
Spies still use certain items while cloaked

### ISSUE THREAD

**Issue by Djrulz0826** [FortyTwoFortyTwo/Randomizer#27]
Spies can charge while cloaked by using 'reload'. Attempting to use 'Mouse2' while on melee toggles cloak and charges.
The Thermal Thruster fully functions while cloaked.
The Manmelter Extinguish ability still works while cloaked.
Related Videos:
https://youtu.be/uQaCF5MC9Wk (Shields)
https://youtu.be/B4MWdZbwBjw (Thermal Thruster)
https://youtu.be/dqeeSJkpooY (Manmelter)

**Comment by FortyTwoFortyTwo** [comment]
[Commit i just did](https://github.com/FortyTwoFortyTwo/Randomizer/commit/f3c6feef58a3f8627e5b1693162b01c4868ca1a1) only fixes spy able to cloak by using attack2 instead of attack3. Able to use weapons while cloaked will be fixed later.
