### ISSUE TITLE
Quick-fix fails to mirror jumps/charges

### ISSUE THREAD

**Issue by Djrulz0826** [FortyTwoFortyTwo/Randomizer#33]
Healing players with the quick-fix results in odd behavior when the player attempts to flare jump/thermal thruster and unfunctional for other blast jumps. Healing regular jumping classes seems to result in more normal behavior.
Related Videos:
https://youtu.be/IKYYCGooCoA (Healing Heavy)
https://youtu.be/EWzDIj449tc (Healing Soldier)

**Comment by FortyTwoFortyTwo** [comment]
I couldn't get to test it myself if this is truly fixed, can you check that?

**Comment by doomy64** [comment]
As far as I can tell, this has been fixed
