### ISSUE TITLE
Sniper causes multiple crashes (client and server)

### ISSUE THREAD

**Issue by doomy64** [FortyTwoFortyTwo/Randomizer#37]
The sniper class causes frequent crashes with certain weapons.

Firing a Righteous Bison, causes the client and somtimes the server to crash.
Swapping to the Fists of Steel, causes the client and sometimes the server to crash.

I'll update this list as I come across more issues.

**Comment by FortyTwoFortyTwo** [comment]
Hard to find clues on which TF2 function causes this to crash. Best can do is to have linux server crash so accelerator extension can dump logs with symbols.

I have [windows log](https://crash.limetech.org/kjqicxakglki) for firing bison, may have to use this if cant get linux.

**Comment by doomy64** [comment]
An interesting note: equipping a gunslinger in slot 3 prevents both of these crashes, although with a side effect of having 25 extra hp and the melee slot is listed as gunslinger

**Comment by FortyTwoFortyTwo** [comment]
Definitely sounds like an issue to sniper's viewmodel animations, as gunslinger overrides it.

I used windows crash log to track down where the crash came from, calls several functions `CBaseCombatWeapon::SendWeaponAnim`, `CBaseCombatWeapon::SetIdealActivity`, `CBaseAnimating::SequenceDuration`, then eventually to `Studio_LocalPoseParameter` [here](https://github.com/TheAlePower/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/public/bone_setup.cpp#L1698l). Either `pStudioHdr` or `seqdesc` param is invalid leading to crash, likely the latter.

Hooking one of those function won't help fix client crash, as it done client side. So I imagine fix would have to be done when client equipped a weapon, similar to [this commit](https://github.com/FortyTwoFortyTwo/Randomizer/commit/da24d1b7a77e76007529366e587bb680ad5ac4a1). Hopefully client side will be able to pickup correct params from server side.

**Comment by Kenzzer** [comment]
Please consider: https://github.com/Kenzzer/JetPack_Fix

It doesn't show up on windows crash dumps that are uploaded on accelerator, but on linux ones yes.
https://crash.limetech.org/buztqktej4ji (for instance)

Using this extension will fix this crash, which isn't inherent to this gamemode. This should be on valve to fix, but my attempts at e-mailing them have proven fruitless.

**Comment by FortyTwoFortyTwo** [comment]
Tried your extension, it seems to be fixed server side, but not client side. May be because this randomizer crash comes from not just force changing class, but also firing weapons, switching weapons etc. Though this may help me look further into where to fix it.

**Comment by doomy64** [comment]
Is it possible to force sniper to use the gunslinger's viewmodels without actually having to equip it? Other than some corner cases where you could end up switching to it, equipping a gunslinger in the pda slot of every sniper has worked fairly well for me.

**Comment by Kenzzer** [comment]
> it seems to be fixed server side, but not **client side.**

That's the first time I hear there's also a client side issue, afaik this crash only affects the server, could you or @doomy64 share a crash dump of your client? I'd like to investigate it then.

**Comment by Kenzzer** [comment]
I'm sorry to insist but I really would like a copy of that client crash you mention. Only the server should be suffering from this, making the extension I linked enough to fix it everywhere, but if there's also a client issue then I'm very interested in investigating it.

#38 landing seems to only delay further the issue

**Comment by FortyTwoFortyTwo** [comment]
I don't have a log of client crash, or i cant find it anywhere in my folder. I'm also just assuming it the same crash trace as server crash, just done clientside but I dont have evidence of that.
