### ISSUE TITLE
As spy, using the dead ringer with the candy cane can drop a health kit

### ISSUE THREAD

**Issue by doomy64** [FortyTwoFortyTwo/Randomizer#43]
When holding a candy cane in hand, triggering your dead ringer will cause you to drop a health kit, regardless of the source of damage.

**Comment by FortyTwoFortyTwo** [comment]
Apparently it [intended from TF2](https://github.com/TheAlePower/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/server/tf/tf_player.cpp#L14993-L15001), no idea why but "fixed" it by just removing the "feature".
