### ISSUE TITLE
Spies can't cloak with stickys/shield

### ISSUE THREAD

**Issue by Djrulz0826** [FortyTwoFortyTwo/Randomizer#46]
Having a stickybomb launcher or shield will prevent the spy from cloaking regardless of what the active weapon is.
The hud says middle click to cloak, but middle clicking does nothing.
Strangely, typing `+attack3` into console will cause the player to constantly cloak and uncloak, as if middle click were being held. (middle click is still bound to `+attack3`)

**Comment by FortyTwoFortyTwo** [comment]
Can't reproduce it myself, sounds like something is wrong with your middle click bind if `+attack3` in console still acts fine.

**Comment by doomy64** [comment]
(Forgot I was on my brother's account when I made this issue)
Turns out my middle click doesn't work in TF2 for some reason. This issue can be closed.
