### ISSUE TITLE
Flying Guillotine sometimes stops recharging as Soldier

### ISSUE THREAD

**Issue by doomy64** [FortyTwoFortyTwo/Randomizer#56]
Soldier with guillotine will lose ammo if it's the active weapon for a short time, and won't regenerate. [Short clip](https://youtu.be/RawSIuK4ZM4)

Touching a resupply locker before using the weapon will prevent this issue, or fix it if it already occurred.

**Comment by FortyTwoFortyTwo** [comment]
This bug seems to be gone now? No idea how or when it was fixed.

**Comment by doomy64** [comment]
I'm still able to reproduce it consistently, although it seems to only occur when you get the weapon for the first time. Kill-binding and respawning with the weapon will cause it to act normally.

**Comment by FortyTwoFortyTwo** [comment]
Seems like this has been fixed from the viewmodels update #110
