### ISSUE TITLE
Sandman stops recharging as Soldier after picking up the ball

### ISSUE THREAD

**Issue by doomy64** [FortyTwoFortyTwo/Randomizer#57]
Soldier with sandman will stop regenerating ammo if the ball is picked up.
I've also had reports of the Wrap Assassin not recharging, but was unable to reproduce it myself

Touching a resupply locker will prevent this issue, or fix it if it already occurred.

**Comment by FortyTwoFortyTwo** [comment]
This bug seems to be gone now? No idea how or when it was fixed.

**Comment by doomy64** [comment]
I'm still able to reproduce it consistently, although it seems to only occur when you get the weapon for the first time. Kill-binding and respawning with the weapon will cause it to act normally.

**Comment by FortyTwoFortyTwo** [comment]
Seems like this has been fixed from the viewmodels update #110
