### ISSUE TITLE
GitHub artifacts expire after 90 days - latest build not available

### ISSUE THREAD

**Issue by FlaminSarge** [FortyTwoFortyTwo/Randomizer#61]
Since it's been 4 months since the last commit, the latest build is not available for download anymore.

**Comment by gentlecolts** [comment]
Why was this closed?  This hasn't stopped being an issue, the current build is also inaccessible for the same reason.  It would be nice of you to provide a persistent package via a release, rather than relying on expiring artifacts

**Comment by FortyTwoFortyTwo** [comment]
Should really use release instead, but @paris-ci already got a lazy method to resolve this /shrug
