### ISSUE TITLE
All players have 2 capture rate

### ISSUE THREAD

**Issue by doomy64** [FortyTwoFortyTwo/Randomizer#76]
Players will cap points with scout's rate regardless of weapons and class.
Some quick and dirty testing showed that `g_iAllowPlayerClass` increments by 2 each time the player resupplies, so there's probably a missing decrement somewhere.

**Comment by FortyTwoFortyTwo** [comment]
Quick look seems to be from `ValidateWearables` hook, increment in both pre and post when there meant to be a decrement in post.
https://github.com/FortyTwoFortyTwo/Randomizer/blob/9e89d3f46386fc7c0b0536c319913f01f57f39f5/scripting/randomizer/dhook.sp#L485

**Comment by FortyTwoFortyTwo** [comment]
Can confirm, fixed it
