### ISSUE TITLE
Resupplying removes wearables

### ISSUE THREAD

**Issue by doomy64** [FortyTwoFortyTwo/Randomizer#77]
Wearables (cosmetic and weapons) get cleared everytime the player touches a resupply locker. Resupplying again restores the weapons, but cosmetics are still removed.

**Comment by FortyTwoFortyTwo** [comment]
`ValidateWearables` is used to set wearables as spy's disguise cosmetic so TF2 doesn't delete it. 
However 2017 leaked code shows `IsPlayerClass` is used, but gone in latest bin decompile. I imagine TF2 devs at one point changed it.

**Comment by FortyTwoFortyTwo** [comment]
Getting this issue, but for weapons instead.

As engineer, having B.A.S.E jumper in primary and/or Shotgun in secondary removes its weapon. Weirdly having B.A.S.E jumper in secondary and/or Shotgun in primary as engineer does not have this issue. Need to look more on which weapons destroys or not.
