### ISSUE TITLE
On Linux, Optimization issue?

### ISSUE THREAD

**Issue by gaejuck** [FortyTwoFortyTwo/Randomizer#84]
When the number of players 24, lag begins. When there are more than 30 players, becomes hard to play.
Reason is unknown because no log appears. 
Performance of the server computer is not bad either.
What's the problem?

**Comment by gaejuck** [comment]
oh thats nice

**Comment by Kenzzer** [comment]
> As for the other detour `CTFPlayer::IsPlayerClass` though, this one detour was really helpful to fix multiple bugs, so simply removing it won't be simple. Best solution probably is to memory patch it, toggle on and off when needed to always return true.

I'm assuming, you're likely to use my mem patch inc, although even if you make your own, that entails the use of `StoreToAddress` regardless, and that function is arguably really slow. So if the intent is to turn off & on a memory patch regularly, you're going to keep having lags. Thankfully, later versions of SM are going to offer a faster `StoreToAddress` but as it stands right now, I don't advise using mem patch in the scope of rapid enabling/disabling.

Good luck solving everything else though!

**Comment by FortyTwoFortyTwo** [comment]
> I'm assuming, you're likely to use my mem patch inc, although even if you make your own, that entails the use of `StoreToAddress` regardless, and that function is arguably really slow. So if the intent is to turn off & on a memory patch regularly, you're going to keep having lags. Thankfully, later versions of SM are going to offer a faster `StoreToAddress` but as it stands right now, I don't advise using mem patch in the scope of rapid enabling/disabling.

Indeed it still lags in 1.10, although it seems to slightly lag a bit less than detour, can't quite confirm it.
I already had progress on this, so may well then push memory patches to master and wait for 1.11 to become stable for new parameter.

**Comment by FortyTwoFortyTwo** [comment]
Well it's been a while, but SM 1.11 is finally stable a few weeks ago, so `StoreToAddress` issues can be resolved. Should hopefully now have much less lags from it.
