### ISSUE TITLE
Building destructions don't display in kill feed

### ISSUE THREAD

**Issue by doomy64** [FortyTwoFortyTwo/Randomizer#91]
Engineer buildings will not show up in the kill feed when destroyed
A sapper being destroyed does not have this issue

**Comment by FortyTwoFortyTwo** [comment]
Does this bug still happens? Couldn't reproduce it myself today.

**Comment by FortyTwoFortyTwo** [comment]
Nevermind, seems like this bug only occurs in Linux while it shows fine in Windows

**Comment by FortyTwoFortyTwo** [comment]
Somewhat fixed it in this [commit](https://github.com/FortyTwoFortyTwo/Randomizer/commit/6b5562b69534dac5c3170291f210bb185527e032), I'm not sure if there a proper solution in dhook gamedata that would work for windows and linux without crashing, so the one param is only in gamedata when in linux.
